// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestModels
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class ListModel : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ListModel\",\"namespace\":\"TestModels\",\"fields\":[{\"name\":\"L" +
				"istKeyString\",\"type\":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"ListKeyInt\",\"ty" +
				"pe\":{\"type\":\"array\",\"items\":\"int\"}}]}");
		private IList<System.String> _ListKeyString;
		private IList<System.Int32> _ListKeyInt;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ListModel._SCHEMA;
			}
		}
		public IList<System.String> ListKeyString
		{
			get
			{
				return this._ListKeyString;
			}
			set
			{
				this._ListKeyString = value;
			}
		}
		public IList<System.Int32> ListKeyInt
		{
			get
			{
				return this._ListKeyInt;
			}
			set
			{
				this._ListKeyInt = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ListKeyString;
			case 1: return this.ListKeyInt;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ListKeyString = (IList<System.String>)fieldValue; break;
			case 1: this.ListKeyInt = (IList<System.Int32>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
