// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace TestModels
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class ValueClass : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ValueClass"",""namespace"":""TestModels"",""fields"":[{""name"":""Value"",""type"":""string""},{""name"":""ValueString"",""type"":""string""},{""name"":""ValueInt"",""type"":""int""},{""name"":""ValueDouble"",""type"":""double""},{""name"":""ValueFloat"",""type"":""float""},{""name"":""ValueDateTime"",""type"":""long""},{""name"":""ValueDecimal"",""type"":""bytes""}]}");
		private string _Value;
		private string _ValueString;
		private int _ValueInt;
		private double _ValueDouble;
		private float _ValueFloat;
		private long _ValueDateTime;
		private byte[] _ValueDecimal;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ValueClass._SCHEMA;
			}
		}
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				this._Value = value;
			}
		}
		public string ValueString
		{
			get
			{
				return this._ValueString;
			}
			set
			{
				this._ValueString = value;
			}
		}
		public int ValueInt
		{
			get
			{
				return this._ValueInt;
			}
			set
			{
				this._ValueInt = value;
			}
		}
		public double ValueDouble
		{
			get
			{
				return this._ValueDouble;
			}
			set
			{
				this._ValueDouble = value;
			}
		}
		public float ValueFloat
		{
			get
			{
				return this._ValueFloat;
			}
			set
			{
				this._ValueFloat = value;
			}
		}
		public long ValueDateTime
		{
			get
			{
				return this._ValueDateTime;
			}
			set
			{
				this._ValueDateTime = value;
			}
		}
		public byte[] ValueDecimal
		{
			get
			{
				return this._ValueDecimal;
			}
			set
			{
				this._ValueDecimal = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Value;
			case 1: return this.ValueString;
			case 2: return this.ValueInt;
			case 3: return this.ValueDouble;
			case 4: return this.ValueFloat;
			case 5: return this.ValueDateTime;
			case 6: return this.ValueDecimal;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Value = (System.String)fieldValue; break;
			case 1: this.ValueString = (System.String)fieldValue; break;
			case 2: this.ValueInt = (System.Int32)fieldValue; break;
			case 3: this.ValueDouble = (System.Double)fieldValue; break;
			case 4: this.ValueFloat = (System.Single)fieldValue; break;
			case 5: this.ValueDateTime = (System.Int64)fieldValue; break;
			case 6: this.ValueDecimal = (System.Byte[])fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
