name: Update Avro Fusion Generator Readme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set NuGet package path as environment variable
        run: echo "PACKAGE_NAME=AvroFusionSource/AvroFusionGenerator/nupkg/" >> $GITHUB_ENV

      - name: Display NuGet package path
        run: |
            echo "NuGet Package Path: ${{ env.PACKAGE_NAME }}"
 job2:
   runs-on: ubuntu-latest
   needs: job1
   strategy:
      matrix:
        configuration: [Debug, Release]
   
   env:
      Solution_Name: AvroFusionGenerator.sln
      Project_Name: AvroFusionGeneratorReadMeUpdater
      Project_Directory: AvroFusionSource/AvroFusionGeneratorReadMeUpdater

   steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install .NET 7 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build the solution
      run: dotnet build $Solution_Name --configuration $Configuration
      env:
        Configuration: ${{ matrix.configuration }}
      shell: bash

    - name: Print build output directory contents
      run: ls -l ${{ env.Project_Directory }}/bin/${{ matrix.configuration }}/net7.0/
      shell: bash

    #- name: Download NuGet package build by AvroFusionGenerator
    #  uses: actions/download-artifact@v2
    #  with:
    #    name: nuget-package
    #    path: artifacts

    #- name: Move NuGet package to read the location
    #  run: |
    #    mv artifacts/AvroFusionGenerator.1.0.0.nupkg AvroFusionSchemaGenerator/AvroFusionSource/AvroFusionGenerator/nupkg/AvroFusionGenerator.1.0.0.nupkg

    - name: Run the executable and update Update README.md
      working-directory: AvroFusionSource/AvroFusionGeneratorReadMeUpdater/bin/${{ matrix.configuration }}/net7.0
      env:
       BUILD_TAGGING_ACCESS_TOKEN: ${{ secrets.BUILD_TAGGING_ACCESS_TOKEN }}
      run: |
       chmod +x AvroFusionGeneratorReadMeUpdater
       ls -l
       ./AvroFusionGeneratorReadMeUpdater
      shell: bash

    - name: Commit updated README.md
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README.md"
        git push
