name: Update Avro Fusion Generator Readme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build ${{ matrix.configuration }}
    strategy:
      matrix:
       configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: AvroFusionGenerator.sln
      Project_Name: AvroFusionGeneratorReadMeUpdater
      Project_Directory: AvroFusionSource/AvroFusionGeneratorReadMeUpdater

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install .NET 7 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet msbuild ${{ env.Project_Directory }}/${{ env.Project_Name }}.csproj 

    - name: Build
      run: dotnet msbuild ${{ env.Project_Directory }}/${{ env.Project_Name }}.csproj /p:Configuration=${{ matrix.configuration }}

    - name: Update README.md
      run: dotnet msbuild ${{ env.Project_Directory }}/${{ env.Project_Name }}.csproj /p:Configuration=${{ matrix.configuration }}

    - name: Commit updated README.md
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README.md"
        git push
