name: Update Avro Fusion Generator Readme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-avrofusion-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install .NET 7 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore path/to/AvroFusionGeneratorReadMeUpdater/AvroFusionGeneratorReadMeUpdater.csproj

    - name: Build
      run: dotnet build path/to/AvroFusionGeneratorReadMeUpdater/AvroFusionGeneratorReadMeUpdater.csproj --configuration Release --no-restore

    - name: Update README.md
      run: dotnet run --project path/to/AvroFusionGeneratorReadMeUpdater/AvroFusionGeneratorReadMeUpdater.csproj

    - name: Commit updated README.md
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README.md"
        git push
