name: Update Avro Fusion Generator Readme

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build ${{ matrix.configuration }}
    strategy:
      matrix:
       configuration: [Debug, Release]

    runs-on: ubuntu-latest

    env:
      Solution_Name: AvroFusionGenerator.sln
      Project_Name: AvroFusionGeneratorReadMeUpdater
      Project_Directory: AvroFusionSource/AvroFusionGeneratorReadMeUpdater

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install .NET 7 SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore
      shell: bash

    - name: Build the solution
      run: dotnet build $Solution_Name --configuration $Configuration
      env:
        Configuration: ${{ matrix.configuration }}
      shell: bash

    - name: Print build output directory contents
      run: ls -l ${{ env.Project_Directory }}/bin/${{ matrix.configuration }}/net7.0/
      shell: bash


    - name: Run the executable
      run: |
        if [ "${{ matrix.configuration }}" == "Debug" ]; then
           cd ${{ env.Project_Directory }}/bin/Debug/net7.0/
           echo "Changing to Debug directory"
           pwd
           echo "Current Debug directory: $(pwd)"
        else
           cd ${{ env.Project_Directory }}/bin/Release/net7.0/
           echo "Changing to Release directory"
           pwd
           echo "Current Release directory: $(pwd)"
        fi
        pwd
        echo "Current directory: $(pwd)"
        chmod +x AvroFusionGeneratorReadMeUpdater.exe
        ls -l
        ./AvroFusionGeneratorReadMeUpdater.exe
      working-directory: ${{ env.Project_Directory }}
      shell: bash


    - name: Update README.md
      run: dotnet run ${{ env.Project_Directory }}/${{ env.Project_Name }}.csproj

    - name: Commit updated README.md
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README.md"
        git push
