// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro.SchemaGeneration.Sample.Model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class AppService : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""AppService"",""namespace"":""Avro.SchemaGeneration.Sample.Model"",""fields"":[{""name"":""AppServiceName"",""type"":""string""},{""name"":""Plan"",""type"":""string""},{""name"":""OperatingSystem"",""type"":""string""},{""name"":""RuntimeStack"",""type"":""string""},{""name"":""Status"",""type"":{""type"":""enum"",""name"":""AppServiceStatus"",""namespace"":""Avro.SchemaGeneration.Sample.Model"",""symbols"":[""Running"",""Stopped"",""Restarting"",""Scaling""]}}]}");
		private string _AppServiceName;
		private string _Plan;
		private string _OperatingSystem;
		private string _RuntimeStack;
		private Avro.SchemaGeneration.Sample.Model.AppServiceStatus _Status;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return AppService._SCHEMA;
			}
		}
		public string AppServiceName
		{
			get
			{
				return this._AppServiceName;
			}
			set
			{
				this._AppServiceName = value;
			}
		}
		public string Plan
		{
			get
			{
				return this._Plan;
			}
			set
			{
				this._Plan = value;
			}
		}
		public string OperatingSystem
		{
			get
			{
				return this._OperatingSystem;
			}
			set
			{
				this._OperatingSystem = value;
			}
		}
		public string RuntimeStack
		{
			get
			{
				return this._RuntimeStack;
			}
			set
			{
				this._RuntimeStack = value;
			}
		}
		public Avro.SchemaGeneration.Sample.Model.AppServiceStatus Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				this._Status = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.AppServiceName;
			case 1: return this.Plan;
			case 2: return this.OperatingSystem;
			case 3: return this.RuntimeStack;
			case 4: return this.Status;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.AppServiceName = (System.String)fieldValue; break;
			case 1: this.Plan = (System.String)fieldValue; break;
			case 2: this.OperatingSystem = (System.String)fieldValue; break;
			case 3: this.RuntimeStack = (System.String)fieldValue; break;
			case 4: this.Status = (Avro.SchemaGeneration.Sample.Model.AppServiceStatus)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
