// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro.SchemaGeneration.Sample.Model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class ArmTemplateMetadata : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ArmTemplateMetadata"",""namespace"":""Avro.SchemaGeneration.Sample.Model"",""fields"":[{""name"":""Sku"",""type"":""string""},{""name"":""PricingPlan"",""type"":""string""},{""name"":""Endpoints"",""type"":""string""},{""name"":""IpAddressRange"",""type"":{""type"":""array"",""items"":""string""}}]}");
		private string _Sku;
		private string _PricingPlan;
		private string _Endpoints;
		private IList<System.String> _IpAddressRange;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ArmTemplateMetadata._SCHEMA;
			}
		}
		public string Sku
		{
			get
			{
				return this._Sku;
			}
			set
			{
				this._Sku = value;
			}
		}
		public string PricingPlan
		{
			get
			{
				return this._PricingPlan;
			}
			set
			{
				this._PricingPlan = value;
			}
		}
		public string Endpoints
		{
			get
			{
				return this._Endpoints;
			}
			set
			{
				this._Endpoints = value;
			}
		}
		public IList<System.String> IpAddressRange
		{
			get
			{
				return this._IpAddressRange;
			}
			set
			{
				this._IpAddressRange = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Sku;
			case 1: return this.PricingPlan;
			case 2: return this.Endpoints;
			case 3: return this.IpAddressRange;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Sku = (System.String)fieldValue; break;
			case 1: this.PricingPlan = (System.String)fieldValue; break;
			case 2: this.Endpoints = (System.String)fieldValue; break;
			case 3: this.IpAddressRange = (IList<System.String>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
