// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro.SchemaGeneration.Sample.Model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class DataFactoryPipeline : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"DataFactoryPipeline\",\"namespace\":\"Avro.SchemaGeneration." +
				"Sample.Model\",\"fields\":[{\"name\":\"PipelineName\",\"type\":\"string\"},{\"name\":\"Descrip" +
				"tion\",\"type\":\"string\"},{\"name\":\"LastModified\",\"type\":\"long\"}]}");
		private string _PipelineName;
		private string _Description;
		private long _LastModified;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return DataFactoryPipeline._SCHEMA;
			}
		}
		public string PipelineName
		{
			get
			{
				return this._PipelineName;
			}
			set
			{
				this._PipelineName = value;
			}
		}
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				this._Description = value;
			}
		}
		public long LastModified
		{
			get
			{
				return this._LastModified;
			}
			set
			{
				this._LastModified = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.PipelineName;
			case 1: return this.Description;
			case 2: return this.LastModified;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.PipelineName = (System.String)fieldValue; break;
			case 1: this.Description = (System.String)fieldValue; break;
			case 2: this.LastModified = (System.Int64)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
