// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro.SchemaGeneration.Sample.Model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class EventGrid : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"EventGrid\",\"namespace\":\"Avro.SchemaGeneration.Sample.Mod" +
				"el\",\"fields\":[{\"name\":\"EventGridName\",\"type\":\"string\"},{\"name\":\"TopicType\",\"type" +
				"\":\"string\"},{\"name\":\"InputSchema\",\"type\":\"string\"}]}");
		private string _EventGridName;
		private string _TopicType;
		private string _InputSchema;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return EventGrid._SCHEMA;
			}
		}
		public string EventGridName
		{
			get
			{
				return this._EventGridName;
			}
			set
			{
				this._EventGridName = value;
			}
		}
		public string TopicType
		{
			get
			{
				return this._TopicType;
			}
			set
			{
				this._TopicType = value;
			}
		}
		public string InputSchema
		{
			get
			{
				return this._InputSchema;
			}
			set
			{
				this._InputSchema = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.EventGridName;
			case 1: return this.TopicType;
			case 2: return this.InputSchema;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.EventGridName = (System.String)fieldValue; break;
			case 1: this.TopicType = (System.String)fieldValue; break;
			case 2: this.InputSchema = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
