// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro.SchemaGeneration.Sample.Model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class ResourceGroup : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ResourceGroup\",\"namespace\":\"Avro.SchemaGeneration.Sample" +
				".Model\",\"fields\":[{\"name\":\"ResourceGroupName\",\"type\":\"string\"},{\"name\":\"Resource" +
				"GroupSubscriptionId\",\"type\":\"string\"},{\"name\":\"CreationDate\",\"type\":\"long\"},{\"na" +
				"me\":\"AppServices\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AppSer" +
				"vice\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"fields\":[{\"name\":\"AppSer" +
				"viceName\",\"type\":\"string\"},{\"name\":\"Plan\",\"type\":\"string\"},{\"name\":\"OperatingSys" +
				"tem\",\"type\":\"string\"},{\"name\":\"RuntimeStack\",\"type\":\"string\"},{\"name\":\"Status\",\"" +
				"type\":{\"type\":\"enum\",\"name\":\"AppServiceStatus\",\"namespace\":\"Avro.SchemaGeneratio" +
				"n.Sample.Model\",\"symbols\":[\"Running\",\"Stopped\",\"Restarting\",\"Scaling\"]}}]}}},{\"n" +
				"ame\":\"ResourceGroupTags\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"Stora" +
				"geAccounts\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"StorageAccoun" +
				"t\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"fields\":[{\"name\":\"StorageAc" +
				"countName\",\"type\":\"string\"},{\"name\":\"AccountType\",\"type\":\"string\"},{\"name\":\"Acce" +
				"ssTier\",\"type\":\"string\"},{\"name\":\"IsSecureTransferEnabled\",\"type\":\"boolean\"}]}}}" +
				",{\"name\":\"VirtualMachines\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\"" +
				":\"VirtualMachine\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"fields\":[{\"n" +
				"ame\":\"VirtualMachineName\",\"type\":\"string\"},{\"name\":\"Size\",\"type\":\"string\"},{\"nam" +
				"e\":\"OperatingSystem\",\"type\":\"string\"},{\"name\":\"Status\",\"type\":{\"type\":\"enum\",\"na" +
				"me\":\"VirtualMachineStatus\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"sym" +
				"bols\":[\"Running\",\"Stopped\",\"Deallocated\",\"Deleting\"]}}]}}},{\"name\":\"DataFactoryP" +
				"ipelines\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"DataFactoryPip" +
				"eline\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"fields\":[{\"name\":\"Pipel" +
				"ineName\",\"type\":\"string\"},{\"name\":\"Description\",\"type\":\"string\"},{\"name\":\"LastMo" +
				"dified\",\"type\":\"long\"}]}}},{\"name\":\"DataFactoryPipelineCount\",\"type\":[\"int\",\"dou" +
				"ble\",\"null\"]},{\"name\":\"EventHubs\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record" +
				"\",\"name\":\"EventHub\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"fields\":[{" +
				"\"name\":\"EventHubName\",\"type\":\"string\"},{\"name\":\"PartitionCount\",\"type\":\"int\"},{\"" +
				"name\":\"MessageRetention\",\"type\":\"long\"}]}}},{\"name\":\"EventGrids\",\"type\":{\"type\":" +
				"\"array\",\"items\":{\"type\":\"record\",\"name\":\"EventGrid\",\"namespace\":\"Avro.SchemaGene" +
				"ration.Sample.Model\",\"fields\":[{\"name\":\"EventGridName\",\"type\":\"string\"},{\"name\":" +
				"\"TopicType\",\"type\":\"string\"},{\"name\":\"InputSchema\",\"type\":\"string\"}]}}},{\"name\":" +
				"\"SchemaGroups\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SchemaGro" +
				"up\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"fields\":[{\"name\":\"GroupNam" +
				"e\",\"type\":\"string\"},{\"name\":\"Description\",\"type\":\"string\"},{\"name\":\"Schemas\",\"ty" +
				"pe\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"EventHubSchema\",\"namespace\"" +
				":\"Avro.SchemaGeneration.Sample.Model\",\"fields\":[{\"name\":\"SchemaName\",\"type\":\"str" +
				"ing\"},{\"name\":\"SchemaVersion\",\"type\":\"string\"},{\"name\":\"SerializationType\",\"type" +
				"\":\"string\"},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"ResourceType\",\"type\":\"strin" +
				"g\"},{\"name\":\"Location\",\"type\":\"string\"},{\"name\":\"ResourceGroup\",\"type\":\"string\"}" +
				",{\"name\":\"SubscriptionId\",\"type\":\"string\",\"aliases\":[\"AzureResourceSubscriptionI" +
				"d\"]},{\"name\":\"ETag\",\"type\":\"string\"},{\"name\":\"AzureResourceTags\",\"type\":{\"type\":" +
				"\"map\",\"values\":\"string\"}},{\"name\":\"ProvisioningState\",\"type\":[\"int\",\"double\",\"nu" +
				"ll\"]}]}}}]}}},{\"name\":\"Schemas\",\"type\":{\"type\":\"array\",\"items\":\"EventHubSchema\"}" +
				"},{\"name\":\"CosmosDBs\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"record\",\"name\":\"Cos" +
				"mosDb\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"fields\":[{\"name\":\"Cosmo" +
				"sDbName\",\"type\":\"string\"},{\"name\":\"AccountType\",\"type\":\"string\"},{\"name\":\"APITyp" +
				"e\",\"type\":\"string\"},{\"name\":\"Databases\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"" +
				"record\",\"name\":\"Database\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"fiel" +
				"ds\":[{\"name\":\"DatabaseName\",\"type\":\"string\"},{\"name\":\"Containers\",\"type\":{\"type\"" +
				":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Container\",\"namespace\":\"Avro.SchemaGen" +
				"eration.Sample.Model\",\"fields\":[{\"name\":\"ContainerName\",\"type\":\"string\"},{\"name\"" +
				":\"PartitionKey\",\"type\":\"string\"},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Resour" +
				"ceType\",\"type\":\"string\"},{\"name\":\"Location\",\"type\":\"string\"},{\"name\":\"ResourceGr" +
				"oup\",\"type\":\"string\"},{\"name\":\"SubscriptionId\",\"type\":\"string\",\"aliases\":[\"Azure" +
				"ResourceSubscriptionId\"]},{\"name\":\"ETag\",\"type\":\"string\"},{\"name\":\"AzureResource" +
				"Tags\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"ProvisioningState\",\"type" +
				"\":[\"int\",\"double\",\"null\"]}]}}},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Resource" +
				"Type\",\"type\":\"string\"},{\"name\":\"Location\",\"type\":\"string\"},{\"name\":\"ResourceGrou" +
				"p\",\"type\":\"string\"},{\"name\":\"SubscriptionId\",\"type\":\"string\",\"aliases\":[\"AzureRe" +
				"sourceSubscriptionId\"]},{\"name\":\"ETag\",\"type\":\"string\"},{\"name\":\"AzureResourceTa" +
				"gs\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"ProvisioningState\",\"type\":" +
				"[\"int\",\"double\",\"null\"]}]}}},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"ResourceTy" +
				"pe\",\"type\":\"string\"},{\"name\":\"Location\",\"type\":\"string\"},{\"name\":\"ResourceGroup\"" +
				",\"type\":\"string\"},{\"name\":\"SubscriptionId\",\"type\":\"string\",\"aliases\":[\"AzureReso" +
				"urceSubscriptionId\"]},{\"name\":\"ETag\",\"type\":\"string\"},{\"name\":\"AzureResourceTags" +
				"\",\"type\":{\"type\":\"map\",\"values\":\"string\"}},{\"name\":\"ProvisioningState\",\"type\":[\"" +
				"int\",\"double\",\"null\"]}]}}},{\"name\":\"AzureResources\",\"type\":{\"type\":\"record\",\"nam" +
				"e\":\"AzureResource\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"fields\":[{\"" +
				"name\":\"Name\",\"type\":\"string\"},{\"name\":\"ResourceType\",\"type\":\"string\"},{\"name\":\"L" +
				"ocation\",\"type\":\"string\"},{\"name\":\"ResourceGroup\",\"type\":\"string\"},{\"name\":\"Subs" +
				"criptionId\",\"type\":\"string\",\"aliases\":[\"AzureResourceSubscriptionId\"]},{\"name\":\"" +
				"ETag\",\"type\":\"string\"},{\"name\":\"AzureResourceTags\",\"type\":{\"type\":\"map\",\"values\"" +
				":\"string\"}},{\"name\":\"ProvisioningState\",\"type\":[\"int\",\"double\",\"null\"]}]}},{\"nam" +
				"e\":\"ArmTemplateMetadata\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"ArmTemplateMeta" +
				"data\",\"namespace\":\"Avro.SchemaGeneration.Sample.Model\",\"fields\":[{\"name\":\"Sku\",\"" +
				"type\":\"string\"},{\"name\":\"PricingPlan\",\"type\":\"string\"},{\"name\":\"Endpoints\",\"type" +
				"\":\"string\"},{\"name\":\"IpAddressRange\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}" +
				"]},{\"name\":\"MappingResources\",\"type\":{\"type\":\"record\",\"name\":\"Tuple4\",\"namespace" +
				"\":\"CustomNamespace\",\"fields\":[{\"name\":\"Item1\",\"type\":\"string\"},{\"name\":\"Item2\",\"" +
				"type\":\"string\"},{\"name\":\"Item3\",\"type\":\"int\"},{\"name\":\"Item4\",\"type\":{\"type\":\"ar" +
				"ray\",\"items\":\"string\"}}]}},{\"name\":\"Sku\",\"type\":\"string\"},{\"name\":\"PricingPlan\"," +
				"\"type\":\"string\"},{\"name\":\"Endpoints\",\"type\":\"string\"},{\"name\":\"IpAddressRange\",\"" +
				"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
		private string _ResourceGroupName;
		private string _ResourceGroupSubscriptionId;
		private long _CreationDate;
		private IList<Avro.SchemaGeneration.Sample.Model.AppService> _AppServices;
		private IDictionary<string,System.String> _ResourceGroupTags;
		private IDictionary<string,Avro.SchemaGeneration.Sample.Model.StorageAccount> _StorageAccounts;
		private IDictionary<string,Avro.SchemaGeneration.Sample.Model.VirtualMachine> _VirtualMachines;
		private IList<Avro.SchemaGeneration.Sample.Model.DataFactoryPipeline> _DataFactoryPipelines;
		private object _DataFactoryPipelineCount;
		private IList<Avro.SchemaGeneration.Sample.Model.EventHub> _EventHubs;
		private IList<Avro.SchemaGeneration.Sample.Model.EventGrid> _EventGrids;
		private IList<Avro.SchemaGeneration.Sample.Model.SchemaGroup> _SchemaGroups;
		private IList<Avro.SchemaGeneration.Sample.Model.EventHubSchema> _Schemas;
		private IDictionary<string,Avro.SchemaGeneration.Sample.Model.CosmosDb> _CosmosDBs;
		private Avro.SchemaGeneration.Sample.Model.AzureResource _AzureResources;
		private Avro.SchemaGeneration.Sample.Model.ArmTemplateMetadata _ArmTemplateMetadata;
		private CustomNamespace.Tuple4 _MappingResources;
		private string _Sku;
		private string _PricingPlan;
		private string _Endpoints;
		private IList<System.String> _IpAddressRange;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ResourceGroup._SCHEMA;
			}
		}
		public string ResourceGroupName
		{
			get
			{
				return this._ResourceGroupName;
			}
			set
			{
				this._ResourceGroupName = value;
			}
		}
		public string ResourceGroupSubscriptionId
		{
			get
			{
				return this._ResourceGroupSubscriptionId;
			}
			set
			{
				this._ResourceGroupSubscriptionId = value;
			}
		}
		public long CreationDate
		{
			get
			{
				return this._CreationDate;
			}
			set
			{
				this._CreationDate = value;
			}
		}
		public IList<Avro.SchemaGeneration.Sample.Model.AppService> AppServices
		{
			get
			{
				return this._AppServices;
			}
			set
			{
				this._AppServices = value;
			}
		}
		public IDictionary<string,System.String> ResourceGroupTags
		{
			get
			{
				return this._ResourceGroupTags;
			}
			set
			{
				this._ResourceGroupTags = value;
			}
		}
		public IDictionary<string,Avro.SchemaGeneration.Sample.Model.StorageAccount> StorageAccounts
		{
			get
			{
				return this._StorageAccounts;
			}
			set
			{
				this._StorageAccounts = value;
			}
		}
		public IDictionary<string,Avro.SchemaGeneration.Sample.Model.VirtualMachine> VirtualMachines
		{
			get
			{
				return this._VirtualMachines;
			}
			set
			{
				this._VirtualMachines = value;
			}
		}
		public IList<Avro.SchemaGeneration.Sample.Model.DataFactoryPipeline> DataFactoryPipelines
		{
			get
			{
				return this._DataFactoryPipelines;
			}
			set
			{
				this._DataFactoryPipelines = value;
			}
		}
		public object DataFactoryPipelineCount
		{
			get
			{
				return this._DataFactoryPipelineCount;
			}
			set
			{
				this._DataFactoryPipelineCount = value;
			}
		}
		public IList<Avro.SchemaGeneration.Sample.Model.EventHub> EventHubs
		{
			get
			{
				return this._EventHubs;
			}
			set
			{
				this._EventHubs = value;
			}
		}
		public IList<Avro.SchemaGeneration.Sample.Model.EventGrid> EventGrids
		{
			get
			{
				return this._EventGrids;
			}
			set
			{
				this._EventGrids = value;
			}
		}
		public IList<Avro.SchemaGeneration.Sample.Model.SchemaGroup> SchemaGroups
		{
			get
			{
				return this._SchemaGroups;
			}
			set
			{
				this._SchemaGroups = value;
			}
		}
		public IList<Avro.SchemaGeneration.Sample.Model.EventHubSchema> Schemas
		{
			get
			{
				return this._Schemas;
			}
			set
			{
				this._Schemas = value;
			}
		}
		public IDictionary<string,Avro.SchemaGeneration.Sample.Model.CosmosDb> CosmosDBs
		{
			get
			{
				return this._CosmosDBs;
			}
			set
			{
				this._CosmosDBs = value;
			}
		}
		public Avro.SchemaGeneration.Sample.Model.AzureResource AzureResources
		{
			get
			{
				return this._AzureResources;
			}
			set
			{
				this._AzureResources = value;
			}
		}
		public Avro.SchemaGeneration.Sample.Model.ArmTemplateMetadata ArmTemplateMetadata
		{
			get
			{
				return this._ArmTemplateMetadata;
			}
			set
			{
				this._ArmTemplateMetadata = value;
			}
		}
		public CustomNamespace.Tuple4 MappingResources
		{
			get
			{
				return this._MappingResources;
			}
			set
			{
				this._MappingResources = value;
			}
		}
		public string Sku
		{
			get
			{
				return this._Sku;
			}
			set
			{
				this._Sku = value;
			}
		}
		public string PricingPlan
		{
			get
			{
				return this._PricingPlan;
			}
			set
			{
				this._PricingPlan = value;
			}
		}
		public string Endpoints
		{
			get
			{
				return this._Endpoints;
			}
			set
			{
				this._Endpoints = value;
			}
		}
		public IList<System.String> IpAddressRange
		{
			get
			{
				return this._IpAddressRange;
			}
			set
			{
				this._IpAddressRange = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.ResourceGroupName;
			case 1: return this.ResourceGroupSubscriptionId;
			case 2: return this.CreationDate;
			case 3: return this.AppServices;
			case 4: return this.ResourceGroupTags;
			case 5: return this.StorageAccounts;
			case 6: return this.VirtualMachines;
			case 7: return this.DataFactoryPipelines;
			case 8: return this.DataFactoryPipelineCount;
			case 9: return this.EventHubs;
			case 10: return this.EventGrids;
			case 11: return this.SchemaGroups;
			case 12: return this.Schemas;
			case 13: return this.CosmosDBs;
			case 14: return this.AzureResources;
			case 15: return this.ArmTemplateMetadata;
			case 16: return this.MappingResources;
			case 17: return this.Sku;
			case 18: return this.PricingPlan;
			case 19: return this.Endpoints;
			case 20: return this.IpAddressRange;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.ResourceGroupName = (System.String)fieldValue; break;
			case 1: this.ResourceGroupSubscriptionId = (System.String)fieldValue; break;
			case 2: this.CreationDate = (System.Int64)fieldValue; break;
			case 3: this.AppServices = (IList<Avro.SchemaGeneration.Sample.Model.AppService>)fieldValue; break;
			case 4: this.ResourceGroupTags = (IDictionary<string,System.String>)fieldValue; break;
			case 5: this.StorageAccounts = (IDictionary<string,Avro.SchemaGeneration.Sample.Model.StorageAccount>)fieldValue; break;
			case 6: this.VirtualMachines = (IDictionary<string,Avro.SchemaGeneration.Sample.Model.VirtualMachine>)fieldValue; break;
			case 7: this.DataFactoryPipelines = (IList<Avro.SchemaGeneration.Sample.Model.DataFactoryPipeline>)fieldValue; break;
			case 8: this.DataFactoryPipelineCount = (System.Object)fieldValue; break;
			case 9: this.EventHubs = (IList<Avro.SchemaGeneration.Sample.Model.EventHub>)fieldValue; break;
			case 10: this.EventGrids = (IList<Avro.SchemaGeneration.Sample.Model.EventGrid>)fieldValue; break;
			case 11: this.SchemaGroups = (IList<Avro.SchemaGeneration.Sample.Model.SchemaGroup>)fieldValue; break;
			case 12: this.Schemas = (IList<Avro.SchemaGeneration.Sample.Model.EventHubSchema>)fieldValue; break;
			case 13: this.CosmosDBs = (IDictionary<string,Avro.SchemaGeneration.Sample.Model.CosmosDb>)fieldValue; break;
			case 14: this.AzureResources = (Avro.SchemaGeneration.Sample.Model.AzureResource)fieldValue; break;
			case 15: this.ArmTemplateMetadata = (Avro.SchemaGeneration.Sample.Model.ArmTemplateMetadata)fieldValue; break;
			case 16: this.MappingResources = (CustomNamespace.Tuple4)fieldValue; break;
			case 17: this.Sku = (System.String)fieldValue; break;
			case 18: this.PricingPlan = (System.String)fieldValue; break;
			case 19: this.Endpoints = (System.String)fieldValue; break;
			case 20: this.IpAddressRange = (IList<System.String>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
