// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Avro.SchemaGeneration.Sample.Model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class SchemaGroup : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""SchemaGroup"",""namespace"":""Avro.SchemaGeneration.Sample.Model"",""fields"":[{""name"":""GroupName"",""type"":""string""},{""name"":""Description"",""type"":""string""},{""name"":""Schemas"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""EventHubSchema"",""namespace"":""Avro.SchemaGeneration.Sample.Model"",""fields"":[{""name"":""SchemaName"",""type"":""string""},{""name"":""SchemaVersion"",""type"":""string""},{""name"":""SerializationType"",""type"":""string""},{""name"":""Name"",""type"":""string""},{""name"":""ResourceType"",""type"":""string""},{""name"":""Location"",""type"":""string""},{""name"":""ResourceGroup"",""type"":""string""},{""name"":""SubscriptionId"",""type"":""string"",""aliases"":[""AzureResourceSubscriptionId""]},{""name"":""ETag"",""type"":""string""},{""name"":""AzureResourceTags"",""type"":{""type"":""map"",""values"":""string""}},{""name"":""ProvisioningState"",""type"":[""int"",""double"",""null""]}]}}}]}");
		private string _GroupName;
		private string _Description;
		private IList<Avro.SchemaGeneration.Sample.Model.EventHubSchema> _Schemas;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return SchemaGroup._SCHEMA;
			}
		}
		public string GroupName
		{
			get
			{
				return this._GroupName;
			}
			set
			{
				this._GroupName = value;
			}
		}
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				this._Description = value;
			}
		}
		public IList<Avro.SchemaGeneration.Sample.Model.EventHubSchema> Schemas
		{
			get
			{
				return this._Schemas;
			}
			set
			{
				this._Schemas = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.GroupName;
			case 1: return this.Description;
			case 2: return this.Schemas;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.GroupName = (System.String)fieldValue; break;
			case 1: this.Description = (System.String)fieldValue; break;
			case 2: this.Schemas = (IList<Avro.SchemaGeneration.Sample.Model.EventHubSchema>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
