// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CustomNamespace
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Tuple4 : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Tuple4\",\"namespace\":\"CustomNamespace\",\"fields\":[{\"name\":" +
				"\"Item1\",\"type\":\"string\"},{\"name\":\"Item2\",\"type\":\"string\"},{\"name\":\"Item3\",\"type\"" +
				":\"int\"},{\"name\":\"Item4\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
		private string _Item1;
		private string _Item2;
		private int _Item3;
		private IList<System.String> _Item4;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Tuple4._SCHEMA;
			}
		}
		public string Item1
		{
			get
			{
				return this._Item1;
			}
			set
			{
				this._Item1 = value;
			}
		}
		public string Item2
		{
			get
			{
				return this._Item2;
			}
			set
			{
				this._Item2 = value;
			}
		}
		public int Item3
		{
			get
			{
				return this._Item3;
			}
			set
			{
				this._Item3 = value;
			}
		}
		public IList<System.String> Item4
		{
			get
			{
				return this._Item4;
			}
			set
			{
				this._Item4 = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Item1;
			case 1: return this.Item2;
			case 2: return this.Item3;
			case 3: return this.Item4;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Item1 = (System.String)fieldValue; break;
			case 1: this.Item2 = (System.String)fieldValue; break;
			case 2: this.Item3 = (System.Int32)fieldValue; break;
			case 3: this.Item4 = (IList<System.String>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
